### ISSUE TITLE
[ERROR] Failed download BuildManifest.plist

### ISSUE THREAD

**Issue by 877dev** [dora2-iOS/Nudaoaddu#2]
Hi, I'm trying to save the special blob for 12.4 iPhone6,2 n53ap. I'm getting the error "/jws/get.sh: line 142: bin/partialZipBrowser: No such file or directory
[ERROR] Failed download BuildManifest.plist", Any help? Thank you.

**Comment by dora2-iOS** [comment]
Move (cd) to the "Nudaoaddu" directory and execute "./get.sh".

**Comment by 877dev** [comment]
Working now, I've ran into another issue though, I created a separate issue.
